services:
  db:
    image: postgres:15-alpine
    restart: always
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      TZ: $TIMEZONE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    networks:
      - mattermost
  mattermost:
    image: mattermost/mattermost-team-edition:7.8
    depends_on:
      - db
    restart: always
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp
    volumes:
      - mattermost:/mattermost
    environment:
      TZ: $TIMEZONE
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable&connect_timeout=10
      MM_EMAILSETTINGS_SMTPSERVER: $SMTP_HOST
      MM_EMAILSETTINGS_SMTPPORT: $SMTP_PORT
      MM_EMAILSETTINGS_SMTPAUTH: $SMTP_AUTH
      MM_EMAILSETTINGS_SMTPUSERNAME: $SMTP_USER
      MM_EMAILSETTINGS_SMTPPASSWORD: $SMTP_PASSWORD
      MM_EMAILSETTINGS_CONNECTIONSECURITY: $SMTP_CONNECTION_SECURITY
      MM_EMAILSETTINGS_SKIPSERVERCERTIFICATEVERIFICATION: $SMTP_SKIP_TLS_VERIFY
      MM_EMAILSETTINGS_FEEDBACKNAME: $SMTP_FROM_NAME
      MM_EMAILSETTINGS_FEEDBACKEMAIL: $SMTP_FROM_EMAIL
      MM_EMAILSETTINGS_REPLYTOADDRESS: $SMTP_REPLY_TO
      MM_SUPPORTSETTINGS_SUPPORTEMAIL: $SUPPORT_EMAIL
      MM_EMAILSETTINGS_SENDEMAILNOTIFICATIONS: true
      MM_SERVICESETTINGS_SITEURL: https://${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.mattermost.entrypoints=websecure"
      - "traefik.http.services.mattermost.loadbalancer.server.port=8065"
    networks:
      - mattermost
      - web
volumes:
  db:
  mattermost:
networks:
  mattermost:
  web:
    name: web
    external: true