version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: outline-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - outline
  db:
    image: postgres:15-alpine
    container_name: outline-db
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      TZ: $TIMEZONE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    networks:
      - outline
  outline:
    image: outlinewiki/outline:0.68.1
    container_name: outline
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        yarn db:migrate --env production-ssl-disabled
        yarn start
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
      PGSSLMODE: disable
      URL: "https://${DOMAIN}"
      SECRET_KEY: $SECRET_KEY
      UTILS_SECRET: $UTILS_SECRET
      FORCE_HTTPS: false
      ENABLE_UPDATES: false
      REDIS_URL: $REDIS_URL
      AWS_ACCESS_KEY_ID: $S3_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: $S3_SECRET_KEY
      AWS_REGION: $S3_REGION
      AWS_S3_UPLOAD_BUCKET_URL: "https://${S3_BUCKET}.s3.${S3_REGION}.${S3_PROVIDER_DOMAIN}"
#      AWS_S3_ACCELERATE_URL:
      AWS_S3_UPLOAD_BUCKET_NAME: $S3_BUCKET
      AWS_S3_UPLOAD_MAX_SIZE: 26214400
      AWS_S3_FORCE_PATH_STYLE: false
      AWS_S3_ACL: private
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_USERNAME: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_FROM_EMAIL: $SMTP_FROM_EMAIL
      SMTP_REPLY_EMAIL: $SMTP_REPLY_EMAIL
      SMTP_SECURE: $SMTP_SECURE
      WEB_CONCURRENCY: 1
      OIDC_CLIENT_ID: $OIDC_CLIENT_ID
      OIDC_CLIENT_SECRET: $OIDC_CLIENT_SECRET
      OIDC_AUTH_URI: $OIDC_AUTH_URI
      OIDC_TOKEN_URI: $OIDC_TOKEN_URI
      OIDC_USERINFO_URI: $OIDC_USERINFO_URI
      OIDC_USERNAME_CLAIM: $OIDC_USERNAME_CLAIM
      OIDC_DISPLAY_NAME: $OIDC_DISPLAY_NAME
      OIDC_SCOPES: $OIDC_SCOPES
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.outline.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.outline.entrypoints=websecure"
      - "traefik.http.services.outline.loadbalancer.server.port=3000"
    depends_on:
      - redis
    networks:
      - outline
      - web

volumes:
  db:
  redis-data:

networks:
  outline:
  web:
    name: web
    external: true