#        # backup
#        gitlab_rails['backup_archive_permissions'] = 0644 # See: https://docs.gitlab.com/ce/raketasks/backup_restore.html#backup-archive-permissions
#        gitlab_rails['backup_keep_time'] = 1468800 # 17 days, we'll do a full backup every 5 days
#        gitlab_rails['backup_upload_connection'] = {
#          'provider' => 'AWS',
#          'region' => 'us-east-1',
#          'aws_access_key_id' => "${S3_ACCESS_KEY_ID_GITLAB_BACKUP}",
#          'aws_secret_access_key' => "${S3_SECRET_ACCESS_KEY_GITLAB_BACKUP}"
#        }
#        gitlab_rails['backup_upload_remote_directory'] = 's3-backup-bucket'
### SMTP Settings https://docs.gitlab.com/omnibus/settings/smtp.html
#gitlab_rails['smtp_enable'] = true
#gitlab_rails['smtp_address'] = "smtp.example.com"
#gitlab_rails['smtp_port'] = 587
#gitlab_rails['smtp_user_name'] = "username"
#gitlab_rails['smtp_password'] = "password"
#gitlab_rails['smtp_domain'] = "example.com"
#gitlab_rails['smtp_authentication'] = "login"
#gitlab_rails['smtp_enable_starttls_auto'] = true
#gitlab_rails['smtp_tls'] = false
#gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
#
### Email Settings
#gitlab_rails['gitlab_email_from'] = 'gitlab@example.com'
#gitlab_rails['gitlab_email_reply_to'] = 'noreply@example.com'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${DOMAIN}/'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        letsencrypt['enable'] = false
#    ports:
#      - "2222:22"  # expose GitLab SSH on port 2222 on the host, as Traefik does not yet support TCP routing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    volumes:
      - config:/config:/etc/gitlab
      - logs:/var/log/gitlab'
      - data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - web
volumes:
  config:
  logs:
  data:
networks:
  web:
    name: web
    external: true