
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${DOMAIN}/'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        letsencrypt['enable'] = false
        gitlab_rails['smtp_enable'] = $SMTP_ENABLED
        gitlab_rails['smtp_address'] = '$SMTP_HOST'
        gitlab_rails['smtp_port'] = $SMTP_PORT
        gitlab_rails['smtp_user_name'] = '$SMTP_USER'
        gitlab_rails['smtp_password'] = '$SMTP_PASSWORD'
        gitlab_rails['smtp_domain'] = '$DOMAIN'
        gitlab_rails['smtp_authentication'] = '$SMTP_AUTH_TYPE'
        gitlab_rails['smtp_enable_starttls_auto'] = $SMTP_STARTTLS_AUTO
        gitlab_rails['smtp_tls'] = $SMTP_FORCE_SSL
        gitlab_rails['smtp_openssl_verify_mode'] = '$SMTP_OPENSSL_VERIFY_MODE'
        gitlab_rails['gitlab_email_from'] = '$SMTP_FROM_EMAIL'
        gitlab_rails['gitlab_email_reply_to'] = '$SMTP_REPLY_TO'
        
        gitlab_rails['backup_archive_permissions'] = 0644 
        gitlab_rails['backup_keep_time'] = $BACKUP_KEEP_TIME
        gitlab_rails['backup_upload_connection'] = {
          'provider' => 'AWS',
          'region' => '$S3_REGION',
          'aws_access_key_id' => '$S3_ACCESS_KEY',
          'aws_secret_access_key' => '$S3_SECRET_KEY',
          'endpoint' => '$S3_ENDPOINT'
        }
        gitlab_rails['backup_upload_remote_directory'] = '$S3_BUCKET'
#    ports:
#      - "2222:22"  # expose GitLab SSH on port 2222 on the host, as Traefik does not yet support TCP routing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - web
volumes:
  config:
    name: gitlab_config
  logs:
    name: gitlab_logs
  data:
    name: gitlab_data
networks:
  web:
    name: web
    external: true